@articleId = 66b219880529fdb5a1cfbb2e
@authorId = 66b23317c27cad262421db52

### Get all articles

GET http://localhost:3000/articles?limit=99

### Create a new article (needs an author id)

POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "Jim posting",
  "content": "This is my first article",
  "author": "{{authorId}}",
  "tags": ["news", "sport"]
}

### Create another article with different tags

POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "The office",
  "content": "A paper company",
  "author": "{{authorId}}",
  "tags": [ "sports"]
}

### Fails to create an article with missing title

POST http://localhost:3000/articles
Content-Type: application/json

{
  "content": "A paper company",
  "author": "{{authorId}}",
  "tags": [ "sports"]
}

### Get an article by id

GET http://localhost:3000/articles/{{articleId}}

### Update an article by id

PUT http://localhost:3000/articles/{{articleId}}
Content-Type: application/json

{
  "title": "A new title"
}

### Delete an article by id

DELETE http://localhost:3000/articles/{{articleId}}

### Filter articles by tags

GET http://localhost:3000/articles?tags=sports

### Filter articles by tags (multiple)

GET http://localhost:3000/articles?tags=news,sport

### Filter by author

GET http://localhost:3000/articles?author=Michael

### Filter articles by limit

GET http://localhost:3000/articles?limit=3

### Filter articles with cursor

GET http://localhost:3000/articles?limit=3&cursor=66b21e7fd6a42a3004a9dac1

### Get articles with author's details

GET http://localhost:3000/articles/with-authors